M48
; DRILL file {KiCad (6.0.1)} date Mon Aug 29 10:58:43 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-29T10:58:43+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X120.5Y-75.3
X120.5Y-105.8
X151.0Y-75.3
X151.0Y-105.8
T0
M30
